### ISSUE TITLE
Need to allow users to specify multiple observed data files

### ISSUE THREAD

**Issue by hsauro** [sys-bio/SBstoat#4]
I've seen two examples now where the observed data is in multiple files.  Either because each file represents a different condition under which the time series was measured or different state variables that have been measured at different time intervals (or both)

Not sure how to deal with this from a user perspective especially if the files represent different conditions, eg because they were measured with different inputs on the experimental system. We might need a different interface for this?

**Comment by joseph-hellerstein** [comment]
Implemented ModelStudy that allows users to specify and compare results for multiple data files.
